from __future__ import annotations

from collections import deque
from functools import lru_cache

import numpy as np

from .symmetry import SymmetryAction

ZERO_THRESHOLD = 1e-10


def _clean_near_zero(v: np.ndarray) -> np.ndarray:
    cleaned = np.asarray(v, dtype=float).copy()
    cleaned[np.abs(cleaned) < ZERO_THRESHOLD] = 0.0
    return cleaned


def _key(v: np.ndarray, tol: float) -> tuple[int, int, int, int]:
    if tol <= 0:
        raise ValueError("tol must be positive")
    q = np.round(v / tol).astype(int)
    return int(q[0]), int(q[1]), int(q[2]), int(q[3])


@lru_cache(maxsize=64)
def _finite_group_elements(
    generator_data: tuple[bytes, ...],
    max_elements: int,
) -> tuple[np.ndarray, ...] | None:
    # Keep full-precision matrices for propagation and only round for the hash
    # key. Rounding the propagated matrix itself compounds floating-point drift
    # at every BFS step, which makes otherwise-finite irrational reflection
    # groups (Coxeter groups with cos(pi/n) entries) look like they never close.
    generators = [np.frombuffer(data, dtype=float).reshape(4, 4) for data in generator_data]
    identity = np.eye(4)
    elements = {tuple(identity.round(8).ravel()): identity}
    pending = deque([identity])

    while pending:
        current = pending.popleft()
        for generator in generators:
            transformed = generator @ current
            key = tuple(transformed.round(8).ravel())
            if key in elements:
                continue
            elements[key] = transformed
            pending.append(transformed)
            if len(elements) > max_elements:
                return None

    return tuple(elements.values())


def group_order(action: SymmetryAction, max_elements: int = 100_000) -> int | None:
    """Return the number of elements in the group generated by `action`.

    Returns None if the group's closure exceeds `max_elements` (treated as
    "too large/infinite to enumerate" rather than a hard error).
    """
    generator_data = tuple(generator.tobytes() for generator in action.generators)
    elements = _finite_group_elements(generator_data, max_elements)
    return None if elements is None else len(elements)


def generate_vertices_from_seed(
    seed: np.ndarray,
    action: SymmetryAction,
    *,
    tol: float = 1e-8,
    max_vertices: int = 20000,
) -> np.ndarray:
    """Generate the orbit of a seed point under generator closure via BFS.

    Repeatedly applies all generators to newly discovered points until closure
    (within tolerance-quantized keys) is reached.
    """
    s = _clean_near_zero(seed)
    if s.shape != (4,):
        raise ValueError(f"Expected seed shape (4,), got {s.shape}")

    generator_data = tuple(generator.tobytes() for generator in action.generators)
    elements = _finite_group_elements(generator_data, max_vertices)
    if elements is not None:
        discovered = {_key(element @ s, tol): element @ s for element in elements}
        return np.vstack(list(discovered.values()))

    discovered: dict[tuple[int, int, int, int], np.ndarray] = {_key(s, tol): s}
    q: deque[np.ndarray] = deque([s])

    while q:
        cur = q.popleft()
        for img in action.apply(cur):
            img = _clean_near_zero(img)
            k = _key(img, tol)
            if k in discovered:
                continue
            discovered[k] = img
            q.append(img)
            if len(discovered) > max_vertices:
                raise RuntimeError(
                    f"Exceeded max_vertices={max_vertices}. "
                    "Group may be very large/infinite under current generators."
                )

    verts = np.vstack(list(discovered.values()))
    return verts
