from __future__ import annotations

from collections import deque
from functools import lru_cache

import numpy as np
from scipy.spatial import cKDTree

from .symmetry import SymmetryAction

ZERO_THRESHOLD = 1e-10


def _clean_near_zero(v: np.ndarray) -> np.ndarray:
    cleaned = np.asarray(v, dtype=float).copy()
    cleaned[np.abs(cleaned) < ZERO_THRESHOLD] = 0.0
    return cleaned


def _key(v: np.ndarray, tol: float) -> tuple[int, int, int, int]:
    """Quantize a 4D vector to a hashable key using tolerance-scaled rounding."""
    if tol <= 0:
        raise ValueError("tol must be positive")
    q = np.round(v / tol).astype(int)
    return int(q[0]), int(q[1]), int(q[2]), int(q[3])


def _dedupe(points: np.ndarray, tol: float) -> np.ndarray:
    """Indices of one representative per cluster of points closer than ``tol`` (first one kept).

    Clustering by distance never splits a point from its own float-noise copy, which
    rounding to a grid does whenever the two copies straddle a rounding boundary.
    """
    pts = np.asarray(points, dtype=float).reshape(len(points), -1)
    parent = np.arange(len(pts))

    def find(i: int) -> int:
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    for i, j in cKDTree(pts).query_pairs(r=tol, output_type="ndarray"):
        a, b = find(int(i)), find(int(j))
        if a != b:
            parent[max(a, b)] = min(a, b)
    return np.array(sorted({find(i) for i in range(len(pts))}), dtype=int)


@lru_cache(maxsize=64)
def _finite_group_elements(
    generator_data: tuple[bytes, ...],
    max_elements: int,
) -> tuple[np.ndarray, ...] | None:
    # Keep full-precision matrices for propagation and only round for the hash
    # key. Rounding the propagated matrix itself compounds floating-point drift
    # at every BFS step, which makes otherwise-finite irrational reflection
    # groups (Coxeter groups with cos(pi/n) entries) look like they never close.
    generators = [np.frombuffer(data, dtype=float).reshape(4, 4) for data in generator_data]
    identity = np.eye(4)
    elements = {tuple(identity.round(8).ravel()): identity}
    pending = deque([identity])

    while pending:
        current = pending.popleft()
        for generator in generators:
            transformed = generator @ current
            key = tuple(transformed.round(8).ravel())
            if key in elements:
                continue
            elements[key] = transformed
            pending.append(transformed)
            if len(elements) > max_elements:
                return None

    # The rounded keys above only prune the search; two float copies of one element can still
    # land on opposite sides of a rounding boundary, so merge those by distance at the end.
    found = np.stack(list(elements.values()))
    return tuple(found[i] for i in _dedupe(found, 1e-6))


def group_order(action: SymmetryAction, max_elements: int = 100_000) -> int | None:
    """Return the number of elements in the group generated by `action`.

    Returns None if the group's closure exceeds `max_elements` (treated as
    "too large/infinite to enumerate" rather than a hard error).
    """
    elements = group_elements(action, max_elements)
    return None if elements is None else len(elements)


def group_elements(
    action: SymmetryAction, max_elements: int = 100_000
) -> tuple[np.ndarray, ...] | None:
    """Return every element of the group generated by `action` (cached), or None if too large."""
    generator_data = tuple(generator.tobytes() for generator in action.generators)
    return _finite_group_elements(generator_data, max_elements)


def is_subgroup(
    action: SymmetryAction,
    parent: SymmetryAction,
    *,
    tol: float = 1e-6,
    max_elements: int = 100_000,
) -> bool:
    """Return True if every generator of `action` is an element of the group `parent` generates.

    Two symmetries can have the same abstract type but live in different
    coordinate bases; this check tells whether they actually act compatibly.
    """
    elements = group_elements(parent, max_elements)
    if elements is None:
        return False
    tree = cKDTree(np.array([element.ravel() for element in elements]))
    distances, _ = tree.query(np.array([g.ravel() for g in action.generators]), k=1)
    return bool(np.max(distances) <= tol)


def generate_vertices_from_seed(
    seed: np.ndarray,
    action: SymmetryAction,
    *,
    tol: float = 1e-8,
    max_vertices: int = 20000,
) -> np.ndarray:
    """Generate the orbit of a seed point under generator closure via BFS.

    For a finite group the orbit is every group element applied to the seed;
    otherwise generators are applied breadth-first until closure. Points closer
    than ``tol`` (scaled by the seed's length when it exceeds 1) are one vertex.
    """
    s = _clean_near_zero(seed)
    if s.shape != (4,):
        raise ValueError(f"Expected seed shape (4,), got {s.shape}")

    elements = group_elements(action, max_vertices)
    if elements is not None:
        images = np.stack(elements) @ s
        images[np.abs(images) < ZERO_THRESHOLD] = 0.0
        return images[_dedupe(images, tol * max(1.0, float(np.linalg.norm(s))))]

    discovered: dict[tuple[int, int, int, int], np.ndarray] = {_key(s, tol): s}
    q: deque[np.ndarray] = deque([s])

    while q:
        cur = q.popleft()
        for img in action.apply(cur):
            img = _clean_near_zero(img)
            k = _key(img, tol)
            if k in discovered:
                continue
            discovered[k] = img
            q.append(img)
            if len(discovered) > max_vertices:
                raise RuntimeError(
                    f"Exceeded max_vertices={max_vertices}. "
                    "Group may be very large/infinite under current generators."
                )

    verts = np.vstack(list(discovered.values()))
    return verts[_dedupe(verts, tol * max(1.0, float(np.linalg.norm(s))))]
