from __future__ import annotations

import numpy as np

from .symmetry import SymmetryAction


def _identity() -> np.ndarray:
    return np.eye(4)


def _swap(i: int, j: int) -> np.ndarray:
    m = np.eye(4)
    m[[i, j]] = m[[j, i]]
    return m


def _sign_flip(i: int) -> np.ndarray:
    m = np.eye(4)
    m[i, i] = -1.0
    return m


def named_symmetry(name: str) -> SymmetryAction:
    """Return built-in symmetry action by name."""
    name = name.strip().lower()

    if name == "identity":
        gens = [_identity()]
    elif name == "coordinate_permutations":
        # Adjacent swaps generate S4 on coordinates.
        gens = [_identity(), _swap(0, 1), _swap(1, 2), _swap(2, 3)]
    elif name == "hyperoctahedral":
        # Signed permutations B4 generated by adjacent swaps + one sign flip.
        # (With swaps, one sign flip can be conjugated to all coordinates.)
        gens = [_identity(), _swap(0, 1), _swap(1, 2), _swap(2, 3), _sign_flip(0)]
    else:
        raise ValueError(
            f"Unknown symmetry '{name}'. "
            "Choose one of: identity, coordinate_permutations, hyperoctahedral"
        )

    return SymmetryAction.from_iterable(gens)


def available_symmetries() -> list[str]:
    return ["identity", "coordinate_permutations", "hyperoctahedral"]
