from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass

import numpy as np
from scipy.spatial import cKDTree

from .generation import group_order
from .library import available_symmetries, named_symmetry
from .symmetry import SymmetryAction


@dataclass(frozen=True)
class OrbitPartition:
    """Container for orbit partition results.

    Attributes:
        orbit_ids: For each input vertex index i, orbit_ids[i] gives the orbit id.
        num_orbits: Number of discovered orbits.
    """

    orbit_ids: list[int]
    num_orbits: int


def compute_orbits(
    vertices: np.ndarray, action: SymmetryAction, tol: float = 1e-8
) -> OrbitPartition:
    """Compute orbit partition (isogonal grouping) for vertices under a symmetry action.

    Orbits are the connected components of the generators' permutations of the
    vertices, which is the same as the group's orbits because the group is
    generated by them.
    """
    verts = np.asarray(vertices, dtype=float)
    if verts.ndim != 2 or verts.shape[1] != 4:
        raise ValueError(f"Expected vertices shape (n,4), got {verts.shape}")

    n = len(verts)
    parent = list(range(n))

    def find(x: int) -> int:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    # Each generator permutes the vertices; match images by distance (not by rounding to a
    # grid, which misses an image whenever it straddles a rounding boundary).
    if n:
        tree = cKDTree(verts)
        for generator in action.generators:
            dist, idx = tree.query(verts @ generator.T, k=1)
            for i in np.flatnonzero(dist <= tol):
                a, b = find(int(i)), find(int(idx[i]))
                if a != b:
                    parent[max(a, b)] = min(a, b)

    orbit_of_root: dict[int, int] = {}
    orbit_ids = []
    for i in range(n):
        orbit_ids.append(orbit_of_root.setdefault(find(i), len(orbit_of_root)))
    orbit_counter = len(orbit_of_root)

    return OrbitPartition(orbit_ids=orbit_ids, num_orbits=orbit_counter)


def matches_symmetry(vertices: np.ndarray, action: SymmetryAction, tol: float = 1e-6) -> bool:
    """Check whether every generator of `action` maps the vertex set onto itself."""
    verts = np.asarray(vertices, dtype=float)
    if len(verts) == 0:
        return True
    tree = cKDTree(verts)
    for generator in action.generators:
        transformed = verts @ generator.T
        distances, _ = tree.query(transformed, k=1)
        if float(np.max(distances)) > tol:
            return False
    return True


def detect_symmetries(
    vertices: np.ndarray,
    tol: float = 1e-6,
    candidates: Iterable[str] | None = None,
) -> list[str]:
    """Return the names of built-in symmetries under which the vertex set is invariant.

    Results are sorted by descending group order (largest/highest symmetry
    first), so `detected[0]` is the highest symmetry found and is the best
    choice for splitting into the largest possible isogonal groups. When
    `candidates` is omitted, alias names for the same group are skipped.
    """
    names = (
        list(candidates)
        if candidates is not None
        else available_symmetries(include_aliases=False)
    )
    matches: list[str] = []
    for name in names:
        try:
            action = named_symmetry(name)
        except ValueError:
            continue
        if matches_symmetry(vertices, action, tol=tol):
            matches.append(name)

    def order_key(name: str) -> int:
        order = group_order(named_symmetry(name))
        return order if order is not None else -1

    matches.sort(key=order_key, reverse=True)
    return matches


def highest_matching_symmetry(
    vertices: np.ndarray,
    tol: float = 1e-6,
    candidates: Iterable[str] | None = None,
) -> str | None:
    """Return the name of the largest-order symmetry matching `vertices`, or None.

    Splitting by this symmetry yields the fewest, largest isogonal orbits
    among all built-in symmetries the vertex set actually satisfies.
    """
    detected = detect_symmetries(vertices, tol=tol, candidates=candidates)
    return detected[0] if detected else None


def combined_matching_action(
    vertices: np.ndarray,
    tol: float = 1e-6,
    candidates: Iterable[str] | None = None,
) -> SymmetryAction | None:
    """Return the action generated by combining every matching candidate, or None.

    Invariance is closed under composition: if the vertex set is invariant
    under each of several candidate symmetries individually, it is also
    invariant under the (usually larger) group generated by all of them
    together. Splitting by this combined action therefore yields the fewest,
    largest possible isogonal orbits achievable from `candidates` -- often
    coarser than any single named symmetry (e.g. picking the true maximal
    subgroup within a "swirl" family instead of one of its named pieces).
    """
    detected = detect_symmetries(vertices, tol=tol, candidates=candidates)
    if not detected:
        return None
    generators: list[np.ndarray] = []
    for name in detected:
        generators.extend(named_symmetry(name).generators)
    return SymmetryAction.from_iterable(generators)


def split_by_orbits(vertices: np.ndarray, partition: OrbitPartition) -> list[np.ndarray]:
    """Split a vertex array into one array per orbit, ordered by orbit id."""
    verts = np.asarray(vertices, dtype=float)
    groups: list[list[np.ndarray]] = [[] for _ in range(partition.num_orbits)]
    for vertex, orbit_id in zip(verts, partition.orbit_ids):
        groups[orbit_id].append(vertex)
    return [np.asarray(group, dtype=float) for group in groups]

